version: '3'
name: stylizer
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    restart: always

  bot:
    build:
      context: ./telegram_bot
      dockerfile: Dockerfile
    volumes:
      - ./bot:/app
    environment:
      TELEGRAM_BOT_TOKEN: 6639128192:AAEV_HHQKuIW_CZ-cA8Gie3pC6nidhb8xzA
      BACKEND_URL: http://nginx
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always
